kids-first/kf-model-fhir

.gitignore, README.md
=> 🐛 Add Vonk server licensing

README.md, kf_model_fhir/app.py
=> 📝 Publish to personal simplifier project

.circleci/config.yml
=> 👷 Validate extensions first in CI

.circleci/config.yml, kf_model_fhir/app.py, kf_model_fhir/cli.py, kf_model_fhir/config.py, tests/test_other.py
=> ✨ Convert XML to JSON for validation + add convert cmd

kf_model_fhir/validation.py, tests/conftest.py, tests/data/profiles/extensions/proband-status.json, tests/data/resources/InvalidParticipant1.json, tests/data/resources/Participant.json, tests/data/singles/bad-ref-extension.json, tests/test_validation.py
=> ✨ Validate extensions 

kf_model_fhir/client.py
=> 🐛 Fix setting of endpoint in client.post_all

scripts/hpo_codesystem.py
Part of https://github.com/d3b-center/clinical-data-flow/issues/36
=> ✨ Add script for making HPO CodeSystem

docs/feedback_and_questions/general_fhir_feedback_and_questions.md, docs/feedback_and_questions/phenopackets_feedback_and_questions.md
Part of https://github.com/d3b-center/clinical-data-flow/issues/39
=> 📝 Create feedback+questions files

kf_model_fhir/app.py, tests/conftest.py, tests/test_app.py
=> ✨ Small validation and error logging improvements

kf_model_fhir/app.py, tests/conftest.py, tests/test_app.py
=> ♻️  Add command includes custom validation

README.md, kf_model_fhir/app.py, kf_model_fhir/loader.py, tests/conftest.py, tests/test_app.py
=> 🐛 Remove old state in IG on update

.gitignore, site_root/input/ImplementationGuide-KidsFirst.json, site_root/input/resources/examples/Patient-pt-001.json, site_root/input/resources/extensions/StructureDefinition-species.json, site_root/input/resources/extensions/StructureDefinition-us-core-ethnicity.json, site_root/input/resources/extensions/StructureDefinition-us-core-race.json, site_root/input/resources/profiles/StructureDefinition-participant.json, site_root/input/resources/search/SearchParameter-species.json, site_root/input/resources/search/SearchParameter-us-core-ethnicity.json, site_root/input/resources/search/SearchParameter-us-core-race.json, site_root/input/resources/terminology/CodeSystem-cdcrec.json, site_root/input/resources/terminology/CodeSystem-species.json, site_root/input/resources/terminology/ValueSet-detailed-ethnicity.json, site_root/input/resources/terminology/ValueSet-detailed-race.json, site_root/input/resources/terminology/ValueSet-omb-ethnicity-category.json, site_root/input/resources/terminology/ValueSet-omb-race-category.json, site_root/input/resources/terminology/ValueSet-species.json
Closes #24 
**Dependencies:**
- Extension
- SearchParameter
- CodeSystem 
- ValueSet
**To do:**
**Mapping Spreadsheet:**
https://docs.google.com/spreadsheets/d/19tQnE75UzvP_k29D-QprbsJ-6ZO2PdUmKPiWHKkcTEg/edit#gid=1197884015
=> ✨ Initial Participant Conformance Resources

site_root/input/ImplementationGuide-KidsFirst.json, site_root/input/resources/examples/Specimen-bs-001.json, site_root/input/resources/extensions/StructureDefinition-concentration.json, site_root/input/resources/profiles/StructureDefinition-biospecimen.json, site_root/input/resources/search/SearchParameter-concentration.json
Closes #25 
**Dependencies:**
**To do:**
**Mapping Spreadsheet:**
https://docs.google.com/spreadsheets/d/19tQnE75UzvP_k29D-QprbsJ-6ZO2PdUmKPiWHKkcTEg/edit#gid=1197884015
=> ✨ Initial Biospecimen Conformance Resources

README.md, docs/naming_conventions.md
Closes #120 
Closes #123 
Closes #127
=> 📝 Update README and Naming Conv docs

kf_model_fhir/mappers/README.md, kf_model_fhir/mappers/common/utils.py, kf_model_fhir/mappers/loader.py, kf_model_fhir/mappers/resources/kfdrc_condition.py, kf_model_fhir/mappers/resources/kfdrc_patient.py
This PR adds a Python mapper for KF DRC Patient resources.
=> ✨ Add KF DRC Patient mapper

kf_model_fhir/mappers/README.md, kf_model_fhir/mappers/loader.py, kf_model_fhir/mappers/resources/kfdrc_specimen.py
This PR adds a Python mapper for KF DRC Specimen resources.
=> ✨ Add KF DRC Specimen Mapper

kf_model_fhir/mappers/README.md, kf_model_fhir/mappers/loader.py, kf_model_fhir/mappers/resources/kfdrc_condition.py, kf_model_fhir/mappers/resources/kfdrc_phenotype.py
This PR adds a Python mapper for KF DRC phenotype resources.
=> ✨ Add KF DRC phenotype Mapper

kf_model_fhir/app.py
=> ♻️ Use indent=2 to write IG json

site_root/input/ImplementationGuide-KidsFirst.json, site_root/input/resources/examples/Observation-vs-001-no-phi.json, site_root/input/resources/examples/Observation-vs-001.json, site_root/input/resources/profiles/StructureDefinition-kfdrc-vital-status-no-phi.json, site_root/input/resources/profiles/StructureDefinition-kfdrc-vital-status.json
=> ✨Initial vital status conformance resources

.circleci/config.yml
=> 🐛 Only publish to simplifier on merge to master

kf_model_fhir/mappers/README.md, kf_model_fhir/mappers/loader.py, kf_model_fhir/mappers/resources/group.py, kf_model_fhir/mappers/resources/kfdrc_patient_relations.py, kf_model_fhir/mappers/resources/kfdrc_research_study.py, site_root/input/ImplementationGuide-KidsFirst.json, site_root/input/resources/examples/Group-fm-001.json, site_root/input/resources/examples/Patient-pt-001.json, site_root/input/resources/examples/Patient-pt-002.json, site_root/input/resources/examples/Patient-pt-003.json, site_root/input/resources/extensions/StructureDefinition-relation.json, site_root/input/resources/extensions/StructureDefinition-species.json, site_root/input/resources/profiles/StructureDefinition-kfdrc-patient.json, site_root/input/resources/search/SearchParameter-relation-note.json, site_root/input/resources/search/SearchParameter-relation-subject.json, site_root/input/resources/search/SearchParameter-relation.json
This PR closes:
- d3b-center/clinical-data-flow#75
- d3b-center/clinical-data-flow#78
=> ✨ Initial family/family_relationship conformance resources/mappers

.github/prepare_assets.sh, .github/release_assets.txt, scripts/update_versions.sh
=> 👷 Add release pre/post PR scripts

.circleci/config.yml, README.md
=> 🔥 Remove publish FHIR resources to Simplifier

scripts/update_versions.sh
You shouldn't need to already be in a working environment to do a release
=> 🐛 Guarantee client before calling fhirutil

README.md
=> 📝 Link to target service plugin docs in readme

kf_model_fhir/ingest_plugin/README.md, kf_model_fhir/ingest_plugin/kids_first_fhir.py, kf_model_fhir/ingest_plugin/target_api_builders/research_subject.py, scripts/integration_test.sh, site_root/input/ImplementationGuide-KidsFirst.json, site_root/input/resources/examples/ResearchSubject-rs-001.json, tests/test_app.py
This PR:
- adds ResearchSubject example resource;
- adds target API builder; 
- updates integration test accordingly; and
- changes ECR
It closes #185 and #195.
=> ✨ Add ResearchSubject example resource and target API builder

scripts/integration_test.sh
Part of kids-first/aws-infra-jenkins-shared-libraries#214
=> ♻️ Always remove the integration test server from Jenkins
